### PR TITLE
Add hash to scheme hex values for editor color highlighting support

### PR DESCRIPTION
**Pull request by JamyGolden**
Having hashes in front of a hex value allows some editors to automatically highlight those colors which makes it easier to work with the schemes files:

Old:
image

New:
image

### CODE REVIEW

**Review by FredHappyface — APPROVED** [review]
Apologies for the delay on reviewing this one! Looks awesome to me. Completely agree with the reasoning for this change

**Review by belak — APPROVED** [review]

**Comment by SenchoPens** [comment]
Hi, please don't change schema so often (I think this is the second time in a year or two you change something and my lib breaks, it's 1000+ users - base16.nix and stylix). It's literally a cosmetic change. Also you broke wezterm's https://wezfurlong.org/wezterm/config/lua/wezterm.color/load_base16_scheme.html.

**Comment by JamyGolden** [comment]
Hey, is there a way you'd like for us to communicate/coordinate with you before making a change in future?

**Comment by SenchoPens** [comment]
You can open an issue in SenchoPens/base16.nix, but generally, if you maintain a standard, you should be careful about backward compatibility, and if breaking it is necessary, prefer doing it in a way which is opt-in for downstream users, e.g. by creating smth like base16_v2 directory. This way issues in the downstream projects will look like "Can you please migrate to this new version?" instead of "Please fix ASAP, everything broke"

**Pull request merged**
